#!/bin/bash
set -u -e -C
shopt -s failglob

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[1;35m'"$@"$'\e[m' >&2; }
function info { echo $'\e[36m'"$@"$'\e[m'; }

function ask_yN {
    local answer=''
    read -n 1 -s -p $'\e[34m'"$* [yN]"$'\e[m' answer
    if test "${answer}" = y; then
        info yes
        return 0
    fi
    info no
    return 1
}


outdir=hsfiles

mkdir -p "${outdir}"

for dir in src/*/; do

    # name of the template
    t="${dir#src/}"
    t="${t%/}"

    while IFS= read -r -d '' path; do

        # Remove one leading `_` from each path name component:
        f="${path/#_}"    # remove at leading position
        f="${f//\/_/\/}"  # remove after a slash

        printf '{-# START_FILE %s #-}\n' "${f}"
        cat "${dir}/${path}"
        echo

    done < <(find "${dir}" -type f -printf '%P\0') >| "${outdir}/${t}.hsfiles"

done
