#!/bin/bash
set -u -e -C
shopt -s failglob


haskell-tempdir "${1:-.}"


# remove cruft from environment

PATH="$(echo "${PATH//:/$'\n'}" | grep -vE '.stack' | paste -s -d:)"

unset HASKELL_PACKAGE_SANDBOX \
      HASKELL_PACKAGE_SANDBOXES \
      STACK_EXE HASKELL_DIST_DIR \
      GHC_ENVIRONMENT \
      GHC_PACKAGE_PATH


echo 'Replacing shell…'

cmd=( env -C "${1:-.}" stack exec env -- -C "${PWD}" "${SHELL}" )

printf '\e[1m$ exec'
printf ' %q' "${cmd[@]}"
printf '\e[m\n'

exec "${cmd[@]}"
