#!/bin/bash
set -u -e -C
shopt -s failglob

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[1;35m'"$@"$'\e[m' >&2; }
function info { echo $'\e[36m'"$@"$'\e[m'; }
function run { printf '\e[1m$'; printf ' %q' "$@"; printf '\e[m\n'; "$@"; }


index=''

case "${1-}" in
    pkg)
        index="$(stack path --local-doc-root)/index.html"
        ;;
    dep)
        index="$(stack path --local-doc-root)/all/index.html"
        ;;
    snap)
        index="$(stack path --snapshot-doc-root)/index.html"
        ;;
esac

if ! test -r "${index}"; then
    run stack build --haddock
fi

if test "${index}"; then
    #addr=127.0.0.1
    #port=8080
    #x darkhttpd "${index%/*}" --addr "$addr" --port "$port"
    #firefox "${addr}:${port}" 
    firefox "${index}"
else
    echo 'Subcommands: pkg, dep, snap'
fi
