#!/bin/bash
set -u -e -C
shopt -s failglob

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[1;35m'"$@"$'\e[m' >&2; }
function info { echo $'\e[36m'"$@"$'\e[m'; }
function run { printf '\e[1m$'; printf ' %q' "$@"; printf '\e[m\n'; "$@"; }

if test -z "${1-}"; then
    err 'Need project name, or try `.` for this directory.'
fi

HASKELL_UTILS_PATH="${BASH_SOURCE%/*}"

if test "${1}" = .; then
    n="$(basename "$(pwd)")"
else
    n="$(basename "${1}")"
    mkdir -p "${1}"
    cd "${1}"
fi
shift

if (shopt -s failglob dotglob; : *) 2>/dev/null; then
    err 'Directory is not empty'
fi

info 'Initialising from stack template'
run stack new --bare "${n}" "$@"


if repo="$(git rev-parse --show-toplevel 2>/dev/null)"; then
    warn "Already in git repo: ${repo}"
else
    info 'Initialising with git defaults'
    git init
    git add .
    run git commit -m initial
fi

"${HASKELL_UTILS_PATH}/hs-tempdir"

run stack build
