#!/bin/bash
set -u -e -C
shopt -s failglob

HASKELL_UTILS_PATH="${BASH_SOURCE%/*}"



"${HASKELL_UTILS_PATH}/hs-tempdir" "${1:-.}"



# remove cruft from environment

PATH="$(echo "${PATH//:/$'\n'}" | grep -vE '.stack' | paste -s -d:)"

unset \
    GHC_ENVIRONMENT \
    GHC_PACKAGE_PATH \
    HASKELL_DIST_DIR \
    HASKELL_PACKAGE_SANDBOX \
    HASKELL_PACKAGE_SANDBOXES \
    STACK_EXE



echo 'Replacing shell…'

cmd=( env -C "${1:-.}" stack exec env -- -C "${PWD}" "${SHELL}" )

printf '\e[1m$ exec'
printf ' %q' "${cmd[@]}"
printf '\e[m\n'

exec "${cmd[@]}"
