#!/bin/bash
set -u -e -C
shopt -s failglob

function err { echo $'\e[1;31m'"$@"$'\e[m' >&2; exit 1; }
function warn { echo $'\e[1;35m'"$@"$'\e[m' >&2; }
function info { echo $'\e[36m'"$@"$'\e[m'; }

cd "${1:-.}"

work='.stack-work'

if ! test -e "${work}"; then
    info 'Set stack build directory to temporary location'
    if test -h "${work}"; then rm "${work}"; fi  # remove stale symlink
    sw="$(mktemp -dt 'stack-work.XXXXXXXX')"
    ln -s "${sw}" "${work}"
fi

if ! test -h "${work}"; then
    warn "Not a symlink: ${work}"
fi
